#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHarness
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NRDAR")]
	public partial class CERCDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCase_Master(Case_Master instance);
    partial void UpdateCase_Master(Case_Master instance);
    partial void DeleteCase_Master(Case_Master instance);
    #endregion
		
		public CERCDBDataContext() : 
				base(global::TestHarness.Properties.Settings.Default.NRDARConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CERCDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CERCDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CERCDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CERCDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vDamageCaseQuery> vDamageCaseQueries
		{
			get
			{
				return this.GetTable<vDamageCaseQuery>();
			}
		}
		
		public System.Data.Linq.Table<Case_Master> Case_Masters
		{
			get
			{
				return this.GetTable<Case_Master>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDamageCaseQuery")]
	public partial class vDamageCaseQuery
	{
		
		private int _CaseID;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<double> _AOUniqueID;
		
		private string _LocationDesc;
		
		private string _Address;
		
		private string _City;
		
		private string _County;
		
		private string _ZipCd;
		
		private string _Country;
		
		private System.Nullable<double> _DecLatVa;
		
		private System.Nullable<double> _DecLongVa;
		
		private System.Nullable<int> _FWSRegionID;
		
		private System.Nullable<bool> _FEDFacility;
		
		private System.Nullable<int> _AOBureau;
		
		private System.Nullable<System.DateTime> _IncidentDt;
		
		private System.Nullable<System.DateTime> _BeginDt;
		
		private System.Nullable<System.DateTime> _EndDt;
		
		private string _StateName;
		
		private string _IncidentType;
		
		private string _Status;
		
		private string _EnteredUID;
		
		private System.Nullable<System.DateTime> _EnteredDt;
		
		private string _ModifiedUID;
		
		private System.Nullable<System.DateTime> _ModifiedDt;
		
		private System.Nullable<bool> _Displayed;
		
		private System.Nullable<bool> _Settled;
		
		private string _Aliases;
		
		private string _Authorities;
		
		private string _Trustees;
		
		private string _Contaminants;
		
		private string _ResponsibleParties;
		
		private string _NaturalResources;
		
		private string _TrusteeResources;
		
		private string _Queryable;
		
		public vDamageCaseQuery()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseID", DbType="Int NOT NULL")]
		public int CaseID
		{
			get
			{
				return this._CaseID;
			}
			set
			{
				if ((this._CaseID != value))
				{
					this._CaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOUniqueID", DbType="Float")]
		public System.Nullable<double> AOUniqueID
		{
			get
			{
				return this._AOUniqueID;
			}
			set
			{
				if ((this._AOUniqueID != value))
				{
					this._AOUniqueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationDesc", DbType="NVarChar(MAX)")]
		public string LocationDesc
		{
			get
			{
				return this._LocationDesc;
			}
			set
			{
				if ((this._LocationDesc != value))
				{
					this._LocationDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(100)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCd", DbType="NVarChar(10)")]
		public string ZipCd
		{
			get
			{
				return this._ZipCd;
			}
			set
			{
				if ((this._ZipCd != value))
				{
					this._ZipCd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(100)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecLatVa", DbType="Float")]
		public System.Nullable<double> DecLatVa
		{
			get
			{
				return this._DecLatVa;
			}
			set
			{
				if ((this._DecLatVa != value))
				{
					this._DecLatVa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecLongVa", DbType="Float")]
		public System.Nullable<double> DecLongVa
		{
			get
			{
				return this._DecLongVa;
			}
			set
			{
				if ((this._DecLongVa != value))
				{
					this._DecLongVa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FWSRegionID", DbType="Int")]
		public System.Nullable<int> FWSRegionID
		{
			get
			{
				return this._FWSRegionID;
			}
			set
			{
				if ((this._FWSRegionID != value))
				{
					this._FWSRegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEDFacility", DbType="Bit")]
		public System.Nullable<bool> FEDFacility
		{
			get
			{
				return this._FEDFacility;
			}
			set
			{
				if ((this._FEDFacility != value))
				{
					this._FEDFacility = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOBureau", DbType="Int")]
		public System.Nullable<int> AOBureau
		{
			get
			{
				return this._AOBureau;
			}
			set
			{
				if ((this._AOBureau != value))
				{
					this._AOBureau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncidentDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> IncidentDt
		{
			get
			{
				return this._IncidentDt;
			}
			set
			{
				if ((this._IncidentDt != value))
				{
					this._IncidentDt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> BeginDt
		{
			get
			{
				return this._BeginDt;
			}
			set
			{
				if ((this._BeginDt != value))
				{
					this._BeginDt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDt
		{
			get
			{
				return this._EndDt;
			}
			set
			{
				if ((this._EndDt != value))
				{
					this._EndDt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="NVarChar(50)")]
		public string StateName
		{
			get
			{
				return this._StateName;
			}
			set
			{
				if ((this._StateName != value))
				{
					this._StateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncidentType", DbType="NVarChar(100)")]
		public string IncidentType
		{
			get
			{
				return this._IncidentType;
			}
			set
			{
				if ((this._IncidentType != value))
				{
					this._IncidentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(3)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredUID", DbType="NVarChar(20)")]
		public string EnteredUID
		{
			get
			{
				return this._EnteredUID;
			}
			set
			{
				if ((this._EnteredUID != value))
				{
					this._EnteredUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnteredDt
		{
			get
			{
				return this._EnteredDt;
			}
			set
			{
				if ((this._EnteredDt != value))
				{
					this._EnteredDt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedUID", DbType="NVarChar(20)")]
		public string ModifiedUID
		{
			get
			{
				return this._ModifiedUID;
			}
			set
			{
				if ((this._ModifiedUID != value))
				{
					this._ModifiedUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDt
		{
			get
			{
				return this._ModifiedDt;
			}
			set
			{
				if ((this._ModifiedDt != value))
				{
					this._ModifiedDt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Displayed", DbType="Bit")]
		public System.Nullable<bool> Displayed
		{
			get
			{
				return this._Displayed;
			}
			set
			{
				if ((this._Displayed != value))
				{
					this._Displayed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settled", DbType="Bit")]
		public System.Nullable<bool> Settled
		{
			get
			{
				return this._Settled;
			}
			set
			{
				if ((this._Settled != value))
				{
					this._Settled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aliases", DbType="NVarChar(MAX)")]
		public string Aliases
		{
			get
			{
				return this._Aliases;
			}
			set
			{
				if ((this._Aliases != value))
				{
					this._Aliases = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authorities", DbType="NVarChar(MAX)")]
		public string Authorities
		{
			get
			{
				return this._Authorities;
			}
			set
			{
				if ((this._Authorities != value))
				{
					this._Authorities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trustees", DbType="NVarChar(MAX)")]
		public string Trustees
		{
			get
			{
				return this._Trustees;
			}
			set
			{
				if ((this._Trustees != value))
				{
					this._Trustees = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contaminants", DbType="NVarChar(MAX)")]
		public string Contaminants
		{
			get
			{
				return this._Contaminants;
			}
			set
			{
				if ((this._Contaminants != value))
				{
					this._Contaminants = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsibleParties", DbType="NVarChar(MAX)")]
		public string ResponsibleParties
		{
			get
			{
				return this._ResponsibleParties;
			}
			set
			{
				if ((this._ResponsibleParties != value))
				{
					this._ResponsibleParties = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaturalResources", DbType="NVarChar(MAX)")]
		public string NaturalResources
		{
			get
			{
				return this._NaturalResources;
			}
			set
			{
				if ((this._NaturalResources != value))
				{
					this._NaturalResources = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrusteeResources", DbType="NVarChar(MAX)")]
		public string TrusteeResources
		{
			get
			{
				return this._TrusteeResources;
			}
			set
			{
				if ((this._TrusteeResources != value))
				{
					this._TrusteeResources = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Queryable", DbType="NVarChar(MAX)")]
		public string Queryable
		{
			get
			{
				return this._Queryable;
			}
			set
			{
				if ((this._Queryable != value))
				{
					this._Queryable = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Case_Master")]
	public partial class Case_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CaseID;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<double> _AOUniqueID;
		
		private string _LocationDesc;
		
		private string _Address;
		
		private string _City;
		
		private System.Nullable<int> _StateCdID;
		
		private string _County;
		
		private string _ZipCd;
		
		private string _Country;
		
		private System.Nullable<double> _DecLatVa;
		
		private System.Nullable<double> _DecLongVa;
		
		private System.Nullable<int> _FWSRegionID;
		
		private System.Nullable<bool> _FEDFacility;
		
		private System.Nullable<int> _AOBureau;
		
		private System.Nullable<System.DateTime> _IncidentDt;
		
		private System.Nullable<System.DateTime> _BeginDt;
		
		private System.Nullable<System.DateTime> _EndDt;
		
		private System.Nullable<int> _IncidentTypeID;
		
		private string _Status;
		
		private string _EnteredUID;
		
		private System.Nullable<System.DateTime> _EnteredDt;
		
		private string _ModifiedUID;
		
		private System.Nullable<System.DateTime> _ModifiedDt;
		
		private System.Nullable<bool> _Displayed;
		
		private System.Nullable<bool> _Settled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCaseIDChanging(int value);
    partial void OnCaseIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAOUniqueIDChanging(System.Nullable<double> value);
    partial void OnAOUniqueIDChanged();
    partial void OnLocationDescChanging(string value);
    partial void OnLocationDescChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateCdIDChanging(System.Nullable<int> value);
    partial void OnStateCdIDChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnZipCdChanging(string value);
    partial void OnZipCdChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnDecLatVaChanging(System.Nullable<double> value);
    partial void OnDecLatVaChanged();
    partial void OnDecLongVaChanging(System.Nullable<double> value);
    partial void OnDecLongVaChanged();
    partial void OnFWSRegionIDChanging(System.Nullable<int> value);
    partial void OnFWSRegionIDChanged();
    partial void OnFEDFacilityChanging(System.Nullable<bool> value);
    partial void OnFEDFacilityChanged();
    partial void OnAOBureauChanging(System.Nullable<int> value);
    partial void OnAOBureauChanged();
    partial void OnIncidentDtChanging(System.Nullable<System.DateTime> value);
    partial void OnIncidentDtChanged();
    partial void OnBeginDtChanging(System.Nullable<System.DateTime> value);
    partial void OnBeginDtChanged();
    partial void OnEndDtChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDtChanged();
    partial void OnIncidentTypeIDChanging(System.Nullable<int> value);
    partial void OnIncidentTypeIDChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnEnteredUIDChanging(string value);
    partial void OnEnteredUIDChanged();
    partial void OnEnteredDtChanging(System.Nullable<System.DateTime> value);
    partial void OnEnteredDtChanged();
    partial void OnModifiedUIDChanging(string value);
    partial void OnModifiedUIDChanged();
    partial void OnModifiedDtChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDtChanged();
    partial void OnDisplayedChanging(System.Nullable<bool> value);
    partial void OnDisplayedChanged();
    partial void OnSettledChanging(System.Nullable<bool> value);
    partial void OnSettledChanged();
    #endregion
		
		public Case_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CaseID
		{
			get
			{
				return this._CaseID;
			}
			set
			{
				if ((this._CaseID != value))
				{
					this.OnCaseIDChanging(value);
					this.SendPropertyChanging();
					this._CaseID = value;
					this.SendPropertyChanged("CaseID");
					this.OnCaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOUniqueID", DbType="Float")]
		public System.Nullable<double> AOUniqueID
		{
			get
			{
				return this._AOUniqueID;
			}
			set
			{
				if ((this._AOUniqueID != value))
				{
					this.OnAOUniqueIDChanging(value);
					this.SendPropertyChanging();
					this._AOUniqueID = value;
					this.SendPropertyChanged("AOUniqueID");
					this.OnAOUniqueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationDesc", DbType="NVarChar(MAX)")]
		public string LocationDesc
		{
			get
			{
				return this._LocationDesc;
			}
			set
			{
				if ((this._LocationDesc != value))
				{
					this.OnLocationDescChanging(value);
					this.SendPropertyChanging();
					this._LocationDesc = value;
					this.SendPropertyChanged("LocationDesc");
					this.OnLocationDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateCdID", DbType="Int")]
		public System.Nullable<int> StateCdID
		{
			get
			{
				return this._StateCdID;
			}
			set
			{
				if ((this._StateCdID != value))
				{
					this.OnStateCdIDChanging(value);
					this.SendPropertyChanging();
					this._StateCdID = value;
					this.SendPropertyChanged("StateCdID");
					this.OnStateCdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(100)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCd", DbType="NVarChar(10)")]
		public string ZipCd
		{
			get
			{
				return this._ZipCd;
			}
			set
			{
				if ((this._ZipCd != value))
				{
					this.OnZipCdChanging(value);
					this.SendPropertyChanging();
					this._ZipCd = value;
					this.SendPropertyChanged("ZipCd");
					this.OnZipCdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(100)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecLatVa", DbType="Float")]
		public System.Nullable<double> DecLatVa
		{
			get
			{
				return this._DecLatVa;
			}
			set
			{
				if ((this._DecLatVa != value))
				{
					this.OnDecLatVaChanging(value);
					this.SendPropertyChanging();
					this._DecLatVa = value;
					this.SendPropertyChanged("DecLatVa");
					this.OnDecLatVaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecLongVa", DbType="Float")]
		public System.Nullable<double> DecLongVa
		{
			get
			{
				return this._DecLongVa;
			}
			set
			{
				if ((this._DecLongVa != value))
				{
					this.OnDecLongVaChanging(value);
					this.SendPropertyChanging();
					this._DecLongVa = value;
					this.SendPropertyChanged("DecLongVa");
					this.OnDecLongVaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FWSRegionID", DbType="Int")]
		public System.Nullable<int> FWSRegionID
		{
			get
			{
				return this._FWSRegionID;
			}
			set
			{
				if ((this._FWSRegionID != value))
				{
					this.OnFWSRegionIDChanging(value);
					this.SendPropertyChanging();
					this._FWSRegionID = value;
					this.SendPropertyChanged("FWSRegionID");
					this.OnFWSRegionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEDFacility", DbType="Bit")]
		public System.Nullable<bool> FEDFacility
		{
			get
			{
				return this._FEDFacility;
			}
			set
			{
				if ((this._FEDFacility != value))
				{
					this.OnFEDFacilityChanging(value);
					this.SendPropertyChanging();
					this._FEDFacility = value;
					this.SendPropertyChanged("FEDFacility");
					this.OnFEDFacilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOBureau", DbType="Int")]
		public System.Nullable<int> AOBureau
		{
			get
			{
				return this._AOBureau;
			}
			set
			{
				if ((this._AOBureau != value))
				{
					this.OnAOBureauChanging(value);
					this.SendPropertyChanging();
					this._AOBureau = value;
					this.SendPropertyChanged("AOBureau");
					this.OnAOBureauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncidentDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> IncidentDt
		{
			get
			{
				return this._IncidentDt;
			}
			set
			{
				if ((this._IncidentDt != value))
				{
					this.OnIncidentDtChanging(value);
					this.SendPropertyChanging();
					this._IncidentDt = value;
					this.SendPropertyChanged("IncidentDt");
					this.OnIncidentDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> BeginDt
		{
			get
			{
				return this._BeginDt;
			}
			set
			{
				if ((this._BeginDt != value))
				{
					this.OnBeginDtChanging(value);
					this.SendPropertyChanging();
					this._BeginDt = value;
					this.SendPropertyChanged("BeginDt");
					this.OnBeginDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDt
		{
			get
			{
				return this._EndDt;
			}
			set
			{
				if ((this._EndDt != value))
				{
					this.OnEndDtChanging(value);
					this.SendPropertyChanging();
					this._EndDt = value;
					this.SendPropertyChanged("EndDt");
					this.OnEndDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncidentTypeID", DbType="Int")]
		public System.Nullable<int> IncidentTypeID
		{
			get
			{
				return this._IncidentTypeID;
			}
			set
			{
				if ((this._IncidentTypeID != value))
				{
					this.OnIncidentTypeIDChanging(value);
					this.SendPropertyChanging();
					this._IncidentTypeID = value;
					this.SendPropertyChanged("IncidentTypeID");
					this.OnIncidentTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(3)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredUID", DbType="NVarChar(20)")]
		public string EnteredUID
		{
			get
			{
				return this._EnteredUID;
			}
			set
			{
				if ((this._EnteredUID != value))
				{
					this.OnEnteredUIDChanging(value);
					this.SendPropertyChanging();
					this._EnteredUID = value;
					this.SendPropertyChanged("EnteredUID");
					this.OnEnteredUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnteredDt
		{
			get
			{
				return this._EnteredDt;
			}
			set
			{
				if ((this._EnteredDt != value))
				{
					this.OnEnteredDtChanging(value);
					this.SendPropertyChanging();
					this._EnteredDt = value;
					this.SendPropertyChanged("EnteredDt");
					this.OnEnteredDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedUID", DbType="NVarChar(20)")]
		public string ModifiedUID
		{
			get
			{
				return this._ModifiedUID;
			}
			set
			{
				if ((this._ModifiedUID != value))
				{
					this.OnModifiedUIDChanging(value);
					this.SendPropertyChanging();
					this._ModifiedUID = value;
					this.SendPropertyChanged("ModifiedUID");
					this.OnModifiedUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDt
		{
			get
			{
				return this._ModifiedDt;
			}
			set
			{
				if ((this._ModifiedDt != value))
				{
					this.OnModifiedDtChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDt = value;
					this.SendPropertyChanged("ModifiedDt");
					this.OnModifiedDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Displayed", DbType="Bit")]
		public System.Nullable<bool> Displayed
		{
			get
			{
				return this._Displayed;
			}
			set
			{
				if ((this._Displayed != value))
				{
					this.OnDisplayedChanging(value);
					this.SendPropertyChanging();
					this._Displayed = value;
					this.SendPropertyChanged("Displayed");
					this.OnDisplayedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settled", DbType="Bit")]
		public System.Nullable<bool> Settled
		{
			get
			{
				return this._Settled;
			}
			set
			{
				if ((this._Settled != value))
				{
					this.OnSettledChanging(value);
					this.SendPropertyChanging();
					this._Settled = value;
					this.SendPropertyChanged("Settled");
					this.OnSettledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
